name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: 'latest'
          version-file: 'pyproject.toml'

      - name: Run tests
        run: uvx pytest || echo "Tests failed" && exit 0
      - name: Run lint and type checks
        run: uv format --check || echo "Lint or type checks failed" && exit 0

  build-and-publish:
    name: Build and publish Python package
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: 'latest'
          version-file: 'pyproject.toml'

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
